### ISSUE TITLE
Incompatibility with "Deeper and Darker" - crash when writing on sign

### ISSUE THREAD

**Issue by DreamyLynn** [Nettakrim/Signed-Paintings#22]
When writing on an echo hanging sign from the mod "Deeper and Darker", Minecraft crashes. On multiplayer servers this also causes chunks to not be rendered properly. Removing Signed Paintings fixes both issues.

MC 1.20.1, Fabric Loader 0.15.7
Signed Paintings 1.0.5-mc1.20+, Deeper and Darker 1.2.6, Fabric API 0.92.0+1.20.1, YetAnotherConfigLib 3.2.2+1.20

https://mclo.gs/hqXEd1F - crash (singleplayer)

https://mclo.gs/lo1fuwk - crash (client, multiplayer)
https://mclo.gs/wbR8z2p - chunks don't render (client, multiplayer)
https://mclo.gs/gxi6SPh - server log
screenshot - chunks don't render (client, multiplayer):
![2024-03-30_10 17 51](https://github.com/Nettakrim/Signed-Paintings/assets/59802880/eba2bb9d-0f11-49f7-a218-e416aff87ac6)

**Comment by Davithy** [comment]
I have this same exact issue with biomes o' plenty signs. I'm assuming this is an issue with all modded signs. It's the same issue too, since I also get the "Non [a-z0-9/._-] character in path of location" issue that causes the player who is editing the signs to crash, and for the chunks to stop rendering. 

I'm on Minecraft 1.20.4, with signed paintings 1.0.5, and Biomes o' plenty 1.20.4 -19.0.0.79

**Comment by Nettakrim** [comment]
yeah this should be fixed in next update but i hit an annoying issue that makes fps bad so its taking a while

**Comment by Nettakrim** [comment]
ok yeah next update soon
